/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zsnails.GameCenter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOError;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;

import com.zsnails.Registro.Registro;
import com.zsnails.game.iCentroJuego;
import com.zsnails.game.iJuego;
import com.zsnails.game.iJugador;
import com.zsnails.game.iRegistro;

/**
 *
 * @author omega
 */
public class GameCenter extends javax.swing.JFrame implements iCentroJuego {

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGame1;
    private javax.swing.JButton btnGame2;
    private javax.swing.JButton btnGame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form GameCenter
     */
    private ArrayList<iJuego> juegos = new ArrayList<>();
    private iJugador jugador = null;
    private JButton[] btns;
    private List<iRegistro> registros = new ArrayList<>();

    public GameCenter(iJugador jugador, iJuego... juegos) {
        initComponents();
        this.jugador = jugador;
        this.btns = new JButton[] { btnGame1, btnGame2, btnGame3 };
        for (iJuego j : juegos)
            this.juegos.add(j);

        this.loadGames();
    }

    @Override
    public ArrayList<iRegistro> getRegistros(iJuego tipoJuego) {
        return new ArrayList<iRegistro>(
                this.registros.stream().filter((r) -> ((Registro) (r)).getJuego().getClass() == tipoJuego.getClass())
                        .toList());
    }

    @Override
    public ArrayList<iJuego> getJuegosDisponibles() {
        // TODO Auto-generated method stub
        return this.juegos;
    }

    private void loadGames() {
        for (int i = 0; i < this.juegos.size(); i++) {
            iJuego juego = this.juegos.get(i);
            if (juego == null)
                continue;
            this.btns[i].setText(this.juegos.get(i).getNombre());

            this.btns[i].addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    juego.iniciarPartida(GameCenter.this.jugador);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGame1 = new javax.swing.JButton();
        btnGame2 = new javax.swing.JButton();
        btnGame3 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("CENTRO DE JUEGOS");

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGame2, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(btnGame3, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(89, 89, 89)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btnGame2, javax.swing.GroupLayout.DEFAULT_SIZE, 57,
                                                        Short.MAX_VALUE)
                                                .addComponent(btnGame1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(btnGame3, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }// GEN-LAST:event_btnExitActionPerformed

    @Override
    public void addRegistro(iRegistro registro) {
        this.registros.add(registro);
        try {
            this.almacenarRegistros();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public javax.swing.JButton getBtnExit() {
        return btnExit;
    }

    public void setBtnExit(javax.swing.JButton btnExit) {
        this.btnExit = btnExit;
    }

    public javax.swing.JButton getBtnGame1() {
        return btnGame1;
    }

    public void setBtnGame1(javax.swing.JButton btnGame1) {
        this.btnGame1 = btnGame1;
    }

    public javax.swing.JButton getBtnGame2() {
        return btnGame2;
    }

    public void setBtnGame2(javax.swing.JButton btnGame2) {
        this.btnGame2 = btnGame2;
    }

    public javax.swing.JButton getBtnGame3() {
        return btnGame3;
    }

    public void setBtnGame3(javax.swing.JButton btnGame3) {
        this.btnGame3 = btnGame3;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public ArrayList<iJuego> getJuegos() {
        return juegos;
    }

    public void setJuegos(ArrayList<iJuego> juegos) {
        this.juegos = juegos;
    }

    public iJugador getJugador() {
        return jugador;
    }

    public void setJugador(iJugador jugador) {
        this.jugador = jugador;
    }

    public JButton[] getBtns() {
        return btns;
    }

    public void setBtns(JButton[] btns) {
        this.btns = btns;
    }

    public List<iRegistro> getRegistros() {
        return registros;
    }

    public void setRegistros(List<iRegistro> registros) {
        this.registros = registros;
    }

    private void cargarRegistros() {
        FileReader fr;
        try {
            fr = new FileReader("data.dat");

            fr.close();
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

    }

    private void almacenarRegistros() throws IOException {
        PrintWriter pw = new PrintWriter(new FileWriter("data.dat"));
        for (int i = 0; i < this.registros.size(); i++) {
            // for (iRegistro _r : this.registros) {
            Registro r = (Registro) this.registros.get(i);
            pw.printf("%s,%s,%d,%b,%s,%s", r.getInicio(), r.getFinalizacion(), r.getPuntaje(), r.getEstadoFinalizado(),
                    r.getJugador().getNombre(), r.getJuego().getNombre());

            if (i != (this.registros.size() - 1)) {
                pw.print("|");
            }
        }
        pw.flush();
        pw.close();
    }
}
